const videos = [
  {
      "id": "nu6q6k5YhKn8ohi",
      "title": "Contoh penyandang disabilitas itu masih bisa bekerja",
      "link": "https://www.youtube.com/embed/SeDcaLx58Ls",
      "desc": [
          "Suhartono (Dirje Binapenta dan PKK): \"Tentunya sebagai wujud dari kehadiran negara dalam upaya pemenuhan amanat UUD 1945 dan tentunya kita juga pun memiliki UU No.8 tahun 2016 tentang penyandang disabilitas. Artinya bahwa kita ini punya regulasi yang memang hak negara harus hadir dan kesempatan kerja baik oleh perusahaan maupun diberikan suatu kebebasan; diberikan kepada kemampuan, minat penyandang disabilitas untuk mengembangkan dirinya. Baik secara kewirausahaan atau sebagai usaha.",
          "Pemerintah harus hadir dalam pemenuhan dari amanat UUD 1945 maupun UU No.8 tahun 2016. Tentunya ini kita melihatnya harus lebih makro lagi. Artinya tidak hanya melihat tenaga kerja yang disabilitas ini ada di perusahaan atau mungkin ada suatu kesempatan bagi penyandang disabilitas ini; Dia juga bisa mengembangkan di dalam perusahaan atau mengembangkan di kewirausahaan.\"",
          "Hindun Anisah (Staf Khusus Menteri Ketenagakerjaan): \"Kegiatan ini baik sekali karena kita tahu bahwa penyandang disabilitas itu adalah bagian dari masyarakat Indonesia dan telah diamanatkan oleh UU No.8 tahun 2016 bahwa penyandang disabilitas itu harus mendapatkan kesempatan pekerjaan yang layak. Oleh karena itu, dimandatkan bahwa setiap perusahaan harus menempatkan, untuk perusahaan swasta minimal 1% dari seluruh jumlah pekerjaannya; itu harus pekerja penyandang yang disabilitas.\"",
          "Edi Purnama (Sesditjen Binapenta dan PKK): \"Kegiatan mengenai pembekalan keterampilan dan pemberian insentif ini, saya kira sangat baik dan perlu diteruskan karena ini adalah merupakan suatu bukti kehadiran pemerintah dalam rangka untuk memberikan hak dan perlindungan kepada penyandang disabilitas. Apalagi dalam situasi pandemi COVID-19 ini.\"",
          "Nora Kartika Setyaningrum (Plt. Direktur PTKDN): \"Kegiatan pembekalan keterampilan kerja dan pemberian insentif peralatan kerja pada kegiatan penanganan tenaga kerja penyandang disabilitas yang terdampak COVID-19 bertujuan agar perusahaan tetap beroperasi dan tenaga kerja penyandang disabilitas tetap berpenghasilan dan bekerja merupakan wujud apresiasi pemerintah kepada dinas yang membidangi Ketenagakerjaan di provinsi, kabupaten/kota sebagai pembina bagi pemberi kerja dan stres jodoh terkait, serta kepada perusahaan yang telah memperkerjakan penyandang disabilitas.\"",
          "Penanganan tenaga kerja penyandang disabilitas terdampak COVID-19 bertujuan agar perusahaan tetap beroperasi dan tenaga kerja penyandang disabilitas tetap berpenghasilan dan bekerja yang diberikan kepada:",
          "PT Chang Shin Indonesia yang merupakan perusahaan dengan skala besar berlokasi di Kabupaten Karawang provinsi Jawa Barat. Perusahaan bergerak di bidang usaha industri manufaktur alas kaki jumlah penyandang disabilitas sebanyak 141 orang dari 17.941 orang karyawan dengan jenis disabilitas tunadaksa, visual impairment, dan tunarungu serta jabatan yang diduduki mereka asisten keep, IT software, maintenance, teknisi, dan operator produksi.",
          "PT Subang Autocomp Indonesia, perusahaan bergerak di bidang industri wiring harness merupakan perusahaan dengan skala besar berlokasi di Kabupaten Subang provinsi Jawa Barat. Jumlah penyandang disabilitas sebanyak 44 orang dari 3.846 orang karyawan dengan jenis disabilitas tunadaksa, tunarungu, tunarungu, tunawicara dan tunagrahita serta jabatan yang diduduki mereka operator produksi.",
          "PT Indomarco Prismatama merupakan perusahaan dengan skala besar berlokasi di kota Jakarta Utara Provinsi DKI Jakarta. Perusahaan bergerak di bidang retail perdagangan besar dan kecil. Jumlah penyandang disabilitas sebanyak 25 orang dari 3.047 orang karyawan dengan jenis disabilitas tunarungu, tunarungu wicara, dan tunadaksa. Sedang jabatannya diduduki mereka store keeper.",
          "PT Pungkook Indonesia One berlokasi di Kabupaten Grobogan provinsi Jawa Tengah. Perusahaan dengan skala besar bergerak di bidang usaha industri manufaktur tas outdoor dan fashion. Jumlah penyandang disabilitas sebanyak 26 orang dari 11.465 orang karyawan dengan jenis disabilitas tunadaksa, tunarungu, tunawicara serta jabatannya diduduki mereka adalah staf, leader, dan operator produksi.",
          "PT Mega Andalan Kalasan merupakan perusahaan dengan skala besar berlokasi di Kabupaten Sleman Daerah Istimewa Yogyakarta. Jumlah penyandang disabilitas sebanyak 10 orang dari 537 orang karyawan dengan jenis disabilitas tunarungu wicara dan tunadaksa jabatannya diduduki mereka staf, kepala unit, kepala regu, kepala bagian, dan operator produksi.",
          "PT Starcam Aparel Indonesia merupakan perusahaan dengan skala besar berlokasi di Kabupaten Jepara provinsi Jawa Tengah. Perusahaan bergerak di bidang industri garmen. Jumlah penyandang disabilitas sebanyak 22 orang dari 2.694 orang karyawan dengan jenis disabilitas tunanetra satu mata dan tunadaksa. Sedangkan jabatan yang diduduki mereka operator produksi, leader, dan staf kantor."
      ],
      "insertedAt": "12 Desember 2022",
      "updatedAt": "2022-12-10T10:27:05.699Z"
  },
  {
      "id": "jsur67GjsHJNa78j3",
      "title": "Penyandang disabilitas yang menginspirasi dunia",
      "link": "https://www.youtube.com/embed/WJmzSr0VNxI",
      "desc": [
          "Balik lagi di channel kita ditokocom. Jalan hidup memang gak bisa ditebak. Ada yang lahir ke dunia dengan fisik sempurna. Ada juga yang lahir dengan keterbatasan. Ada yang ketika lahir diberkahi dengan fisik tanpa celah. Tapi kemudian peristiwa naas menimpa dan menjadikannya disabilitas. Namun, hebatnya banyak dari mereka yang gak menjadikan kekurangan fisik sebagai halangan untuk berprestasi. Keterbatasan itu justru menjadikan motivasi untuk berusaha lebih keras dalam meraih mimpi. Yuk simak lima kisah seorang yang memiliki keterbatasan fisik yang menginspirasi berikut ini.",
          "Yang pertama ada Anthony Robles. Anthony merupakan seorang pegulat yang memenangkan kejuaraan NCAA (National Collegiate Athletic Association) 2010-2011 sebagai pegulat yang ditujuk dalam kelas berat 125 ton. Meskipun terlahir hanya dengan satu kaki. Robles menolak menggunakan kaki palsu. Orang tuanya sebenarnya memberikannya kaki palsu. Namun, saat usia 3 tahun ia mencopotnya.",
          "Setelah itu, ia lebih suka menggunakan perut untuk berjalan. Justru dengan selalu mengandalkan satu kaki ini lah kekuatannya menjadi terbentuk. Pada saat duduk di kelas enam ia mencetakkan rekor di sekolahnya karena bisa push up paling banyak dibandingkan teman-temannya yang normal. Dan saat duduk di kelas delapan, ia juga mulai belajar gulat. Pada awalnya hanya melihat saudara sepupunya bermain gulat. Namun, lama-kelamaan ia tertarik juga dan mulai berlatih di sekolah.",
          "Tak lama kemudian, ia ikut bertanding dan bahkan ikut kejuaraan gulat di berbagai negara Arizona. Ia terus menang sampai membukukan rekor 46 baik di tingkat SMP maupun SMA. Hingga ia menyelesaikan SMAnya dan membukukan rekor beratnya dengan skor 129-15. Catatan prestasi. Menakjubkan bukan?. Rodels melanjutkan kuliah ke Arizone State University. Saat ini lah membangun karir untuk menjadi juara gulat nasional pada kejuaraan gulat Dunia di kelas 55 kg freestyle tahun 2006. Dan ia berhasil sebagai juara ke-enam loh!",
          "Lalu pada tahun keduannya sebagai pegulat perguruan tinggi di tahun 2008-2009, Rodels mendapatkan gelar kehormatan All-American Honors. Kemenangan dan sikap Anthony Robles itu tentunya menginspirasi banyak anak-anak muda di Amerika Serikat bahwa kekurangan bukan berarti kelemahan, tetapi bisa juga menjadi kekuatan. Ia membuktikan dengan menjadi juara gulat nasional mengalahkan orang-orang beranggota tubuh memel dan kuat.",
          "Selanjutnya ada Nick Vujicic. Nick merupakan seorang manusia tanpa lengan dan juga kaki. Akibat kondisi fisiknya, ia kesulitan mendapatkan teman bermain semasa kecil. Nick yang lahir r Desember 1892 merupakan putra dari keluarga yang sederhana. Ibunya seorang bidan dan perawat anak. Sedangkan ayahnya bekerja di kantor administrasi dan akutansi keuangan sekaligus sebagai penginjil.",
          "Namun, siapa sangka Nick belajar banyak dari apa yg dia alami selama hidupnya. \"Tanpa lengan dan tungkai, aku bisa menaklukkan dunia.\" Begitu salah satu kutipan buku yang berjudul Life without Limit yanga ditulis oleh Nick. Nick lahir tanpa lengan dan tungkai atau sering disebut sindrom tetra amelia. Dia memiliki kaki mungil di bagian kaki kirinya yang ia gunakan untuk menggulingkan badan, menendang, menulis, mengetik, dan aktivitas lainnya. Ketika memasuki usia sekolah, Ibu Nick memasukkannya ke sekolah normal pada umumnya. Saat itu, sang ibu berharap agar anaknya bermain dengan anak-anak normal.",
          "Namun, Nick justru mengalami masa-masa sulit di usianya itu. Dia bahkan pernah mencoba bunuh diri karena frustasi atas apa yang dia miliki. Meskipun begitu, Nick akhirnya berhasil menyelesaikan sekolah dan bahkan lulus dari universitas. Nick juga telah menulis beberapa buku inspiratif yang berisi perjalanan hidupnya. Isi buku Nick tidak jauh dari bagaimana ia bangkit dari keterburukan kondisi fisiknya.",
          "Bahkan sekarang Nick menjadi seorang motivator sekaligus penginjil. Ia rutin melakukan perjalanan untuk memotivasi banyak orang. Dan pada bulan Agustus 2013 yang lalu, Nick sempat berkunjung ke Indonesia dan mengisi acara di salah satu program di stasiun televisi. Siapa yang sempat liat Nick kemarin. Wah! Beruntung banget kalian.",
          "Selanjutnya ada seorang jenius yang mendedikasikan hidupnya untuk membuka rahasia alam semesta. Kisah hidupnya digambarkan dalam film The Theory of Everything pada 2014. Dia adalah Stephen Hawking yang lahir pada 8 Januari 1942. Dia merupakan seorang modern ilmuwan yang paling terkenal sekaligus profesor dan penulis yang melakukan berbagai banyak terobosan dalam fisika dan kosomologi.",
          "Buku-bukunya banyak membantu dunia sains sehingga dapat diakses semua orang. Pada usia 21 tahun, Hawking didiagnosa menderita ALS (Amyotrophic Lateral Sclerosis). ALS itu merupakan penyakit motorik neuron yang menyerang saraf pengerak tubuh. Ini tentu membuatnya harus menghabiskan hampir seluruh hidupnya di kursi roda. Hebatnya, ia melawan semua ramalan tentang apa yang akan dia jalani selama beberapa tahun setelah didiagnosa penyakit tersebut. Mobilitas yang melemah dan kondisi lumpuh, gak menghentikan Hawking berpidato dan mampu berkomunikasi. Meski hanya melalui fitur komputer.",
          "Stephen bukan hanya mengajarkan kita teori fisika dan alam semesta. Akan tetapi juga mengajarkan bagaimana sebuah kekuatan mental dan pikiran yang tangguh di dalam tubuh yang sangat lemah. Dan tidak menjadikan kondisi kesehatannya sebagai sebuah excuse atau alasan kegagalan. Justru sebaliknya dengan hebatnya, ia memilih untuk maju. Terima kasih untuk semua ilmunya ya.",
          "Selanjutnya ada Qian Hongyan. Qian Hongyan adalah sebuah gadis difabel asal China yang berhasil menjadi atlet renang. Pada tahun 2000, ia kehilangan kedua kakinya dalam kecelakaan mobil. Sejak umur 4 tahun Qian tak lagi memiliki kaki dan pada akhirnya keluarganya mensiasatinya menggunakan bola basket yang dilubangi dan dibalutkan ke tubuh bawah Qian.",
          "Ia berjalan menggunakan dua kayu berbentuk sendok semen yang digenggam kedua tangannya. Kondisi tersebut membuat Qian mendapat julukan gadis bola basket. Pada 2005, ia menerima bantuan kaki palsu dari Rehabilitation Centre di Beijing. Setelah mendapat perhatian publik, ia juga dibawa ke Beijing untuk menerima kaki palsu pada 20 Maret 2007. Kemudian pada 5 Desember 2013, ia mendapatkan kaki buatan lagi yang cocok dengan ukuran tubuhnya yang sudah beranjak dewasa.",
          "Qian akhirnya menemukan peluang untuk berprestasi. Dia bergabung dengan club renang lokal khusus difabel bernama Yunzhinan Swimming Club. Club renang yang diresmikan pada Agustus 2007 ini, melatih anak-anak difabel usia 10-22 tahun untuk mengikuti kompetisi. Ia mendapat sponsor dari Yunnan Provincial Federation. Ia mengaku pada awalnya, ia sempat kesulitan. Tapi kesulitan tersebut gak membuat dia berhenti. Semakin lama, ia semakin lihai dalam berenang. Setiap harinya Qian berlatih selama 4 jam. Dia berharap suatu saat dapat memenangkan mendali untuk negaranya dalam kompetisi.",
          "Qian yang dulu dipanggil sebagai gadis bola basket, kini justru menjadi orang terkenal di China. Laporan-laporan mengenai perkembangan kaki buatannya sering kali menjadi berita nasional. Kepopulerannya bahkan menyebar sampai ke luar negeri. Foto-fotonya juga menjadi viral di media sosial. Wah, jadi terkenal bangetkan gadis bola basket ini. Salut buat kamu, Qian.",
          "Yang terakhir dateng dari Indonesia yaitu Habibie Afsyah. Seorang penyandang difabel yang lahir di Jakarta, 6 Februari 1988. Bungsu dari 8 bersaudara ini menderita penyakit Muscular Dystrophy. Penyakit yang merusak saraf motorik di otak kecilnya. Sehingga menyebabkan ia semakin mengecil dan lumpuh. Alhasil, Habibie sepanjang hidupnya harus menggunakan kursi roda. Menjelang usia 1 tahun Habibie terdeteksi mengidap kelainan bawaan pada saraf motoriknya.",
          "Setelah melewati masa usia balita, pertumbuhannya terhambat dan mengalami keterbatasan fisik karena saraf-saraf motoriknya rusak. Bahkan ada dokter yang memprediksi umurnya hanya sampai 25 tahun saja. Namun, Habibie tidak bisa menjalani hidup. Seakan hidup seperti 1.000 lagi sikapnya penuh dengan optimisme ke depan. Ia bisa membuktikan bahwa keterbatasan fisik bukan penghambat bagi seseorang untuk maju. Pada akhirnya ia berhasil mengembangkan usaha bisnis online di rumah dengan bergabung di situs bisnis affiliate pada Amazon. Lewat bisnisnya ini sekurang-kurangnya ia mampu menghasilkan 10 juta tiap bulan loh.",
          "Keberhasilan Habibie bahkan membuatnya menjadi salah satu trainer di Eprofitmatrix bersama gurunya, Suwandi Chow, di usianya yang masih 20 tahun. Sejak itu, Habibie sering diundang menjadi pembicara seminar internet marketing di kampus-kampus. Tak ingin sukses sendiri, Habibie membuat wadah bagi penyandang difabel lainnya agar bisa menemukan potensi diri melalui Yayasan Habibie Afsyah.",
          "Keberhasilan Habibie itu gak lepas dari peran orang tuanya Endang Sutyanti dan Nasori Sugianto. Sejak diberitahu perihal penyakit Habibie, sebagai orang tua, mereka memiliki keinginan yang kuat agar anaknya mendapatkan perlakuan layak dari lingkungan sekitar dan menyekolahkan anaknya juga di sekolah umum. Kebetulan Habibie memiliki kecerdasan di atas rata-rata anak normal. Dan setelah lulus SMA, sang bunda rela menjual mobil demi mendaftarkan Habibie khusus internet marketing. Disitulah Habibie mulai menekuni bisnis online.",
          "Dan Tuhan gak pernah diam membiarkan hambanya yang punya kemauan kuat. Akhirnya usaha Habibie di bisnis online mengantarkan Habibie menjadi mandiri dan sukses secara finansial. Kini ia dikenal sebagai pengusaha sukses dan seorang motivator. Tuh buat kalian yang sehat tapi masih banyak ngeluh dan malas-malasan, malu ya sama Habibie. Habibie aja sudah jadi pengusaha sukses sekaligus motivator. Kamu gimana ?"
      ],
      "insertedAt": "12 Desember 2022",
      "updatedAt": "2022-12-08T15:56:37.887Z"
  },
  {
      "id": "Kja8-jdl8Ja9iwn",
      "title": "Saya tidak memiliki tangan dan kaki. Apa alasan kalian? – Nick Vujicic Subtitle Bahasa Indonesia",
      "link": "https://www.youtube.com/embed/yDpqGa5-WdI",
      "desc": [
          "Nick Vujicic terlahir tanpa tangan dan kaki. Meskipun demikian, dia sudah belajar untuk berenang, berselancar, terjun payung, dan berbicara di depan ribuan orang. Nick juga merupakan seorang pimpinan dari 2 perusahaan dan memperkerjakan 12 pekerjaan.",
          "Terutama di tahun-tahun awal sekolah, banyak anak-anak yang datang dan mengejekku.",
          "\"Nick kamu tidak cukup bagus\"",
          "\"Nick menyerah saja\"",
          "\"Nick kamu tidak akan mendapatkan pekerjaan.\"",
          "\"Kamu tidak akan nikah!\"",
          "\"Kamu bahkan tidak bisa pegang tangan istrimu!\"",
          "\"Ayah macam apa kamu? Apabila tidak bisa menggendong anak ketika mereka menangis.\"",
          "\"Kamu sendirian.\"",
          "\"Tentu orang tuamu bisa memelukmu.\"",
          "\"Tetapi pelukan mereka tidak bisa menyembuhkanmu Nick!\"",
          "\"Menyerah saja Nick!\"",
          "\"Menyerah saja!\"",
          "\"Menyerah saja!\"",
          "\"Menyerah saja!\"",
          "\"Menyerah saja!\"",
          "Tema pesan yang diberikan ke aku untuk disampaikan adalah merubah 'tembok' menjadi 'pintu-pintu'. Kalimat yang saya suka pakai adalah merubah rintangan menjadi kesempatan. Aku tahu bahwa terdapat milyaran orang yang sedang kelaparan. Aku tahu di tahun ini akan terdapat jutaan orang ingin bunuh diri. Aku tahu hari ini terdapat 120 juta orang sebagai budak seks. Dan aku pernah bertemu dengan budak seks. Dan aku pernah bertemu lapisan piramida paling atas seperti: Pengusaha, Aku pernah bertemu dengan milyader. Aku pernah bertemu bankir.",
          "Dan aku juga pernah bertemu dengan yatim piatu. Kita semua mencari sesuatu. Kita semua mencari sebuah 'harapan'. Hanya karena kamu terlahir dengan 'harapan'? Bukan! Kita terlahir dengan rasa sakit. Kita terlahir  dan hidup melalui kesulitan. Di kehidupan, orang tuaku selalu mengajarikan bahwa walaupun aku tidak tahu kenapa terlahir dengan kondisi ini. Kita akan selalu memiliki pilihan. Apakah akan marah atas apa yang tidak kita miliki atau bersyukur atas apa yang kita miliki. Dunia adalah tempat yang menyakitkan. Dunia butuh harapan dan rasa cinta. Tanpa harapan, kita akan merasa kenapa kita berada di dunia.",
          "Di usia 8 tahun aku pikir aku harus bunuh diri. Di usia 10 tahun, aku mencoba untuk menenggelamkan diri di 6 inci atau 15 cm air. Di rumahku, aku bilang ke ayahku bahwa aku hanya mau bersantai. Tapi sungguh, aku mau menyelesaikan hidup saya. Saya sudah merasa cukup. Mengapa? Karen pada saat itu aku tidak memiliki harapan. Aku sempat berpikir tidak memiliki harapan. Tetapi hari ini kamu bisa melihat bahwa aku memiliki harapan. Aku pernah berbicara di 5 kongres dan bertemu 7 Presiden.",
          "Penonton terbesar aku sebanyak 110 ribu orang dan aku memiliki 30 ribu undangan untuk berbicara. Dan aku sudah berbicara di hadapan 4,5 juta orang secara langsung di 48 jam terakhir di sini (Serbia). Dan saya sudah menyentuh 5 juta orang lewat media. Aku punya 2 organisasi, aku punya satu perusahaan non-profit dan satu lagi perusahaan for-profit. Aku memiliki istri yang menawan, aku tidak membutuhkan tangan untuk memegang tangannya. Aku hanya mau memegang hatinya. Bagaimana cara aku untuk memeluk anakku? Sangat banyak anak-anak menghampiriku. Sangat luar biasa! Mereka meletakan tangan mereka dan memeluk aku di leher.",
          "Dan aku menyadari di dalam hidup, bahkan bagian terburuk dalam hidup bisa dirubah menjadi bagus. Dan bahkan lebih spesial. 2 hari terbaik di dalam kehidupan seseorang. Hari dimana kamu dilahirkan dan hari dimana kamu mengerti kenapa kamu dilahirkan. Terdapat tujuan besar dalam hidup aku. Aku terlahir karena suatu alasan. Tentu, aku tidak mendapatkan keajaiban. Tetapi aku menyadari sesuatu. Jika Tuhan tidak merubah keadaan aku, Tuhan akan menggunakan kehidupanku untuk menjadi keajaiban bagi orang lain. Ketika kamu tidak mendapatkan keajaiban, kamu tetap bisa menjadi keajaiban bagi orang lain.",
          "Apabila kamu belum memahami siapa dirimu dan kenapa kamu terlahirkan. Aku mau kamu tahu, dengan begitulah aku mengatasinya. Aku tidak memiliki tembok (keterbatasan). Buku aku berjudul 'Hidup tanpa batasan'. Apa yang akan terjadi, terjadilah. Aku tampil di film pendek dengan 30 penghargaan, aku mendapatkan predikat aktor terbaik. Aku membuat video musik. Aku telah menulis 2 buku. Buku pertama dalam 30 bahasa dan terjual 800 ribu buku. Aku berusia 29 tahun dan kita tahu milyaran orang mengetahui siapa aku. Bukan untuk mengangkat harga diri dan statusku, percayalah. Aku sama seperti kalian. Tetapi, aku berharap kalian terinspirasi untuk mengetahui bahwa apabila aku bisa bermimpi besar, kalian juga bisa!",
          "Hal indah sering kali datang dari keadaan yang sangat sulit dan bahkan mustahil. Tetapi ketika kita percaya bahwa Tuhan memiliki alasan dan kita menerima serta bekerja keras, percayalah akan selalu ada jalan."
      ],
      "insertedAt": "12 Desember 2022",
      "updatedAt": "2022-12-08T15:57:42.491Z"
  },
  {
      "id": "VVUF9ajkq3UDeBh",
      "title": "KICK ANDY - DISABILITAS TAPI KEREN",
      "link": "https://www.youtube.com/embed/-Eo-ICzX2no",
      "desc": [
          "Andy: \"Sejak kecil kakinya bermasalah. Katanya tulangnya rapuh sehingga sering patah dan hingga dewasa ia harus menggunakan tongkat untuk berjalan. Tapi mengapa saya mengundang tamu kita ini ke Kick Andy. Mari kita sambut Anjas Pramono. Anjas, apa kabar ? Tos dulu! sehat ?\"",
          "Anjas: \"Alhamdulillah\"",
          "Andy: \"Dateng dari mana ?\"",
          "Anjas: \"Dateng dari Kudus.\"",
          "Andy: \"Umur berapa sekarang ?\"",
          "Anjas: \"Sekarang jadi umur 21 tahun.\"",
          "Andy: \"Boleh tahu apa yang terjadi pada kakimu Anjas ?\"",
          "Anjas: \"Mengidap salah satu penyakit yang lumayan langka.\"",
          "Andi: \"Apa itu ?\"",
          "Anjas: \"Namanya osteogenesis imperfecta. Osteogenesis imperfecta adalah kerapuhan tulang di masa kanak-kanak ya. Terlambat pengerasan, lebih tepatnya begitu. Nah, di situ saya selama kecil sampai mungkin kelas 5 SD itu saya sangat rapuh. Dari balita total patah tulang mungkin sekitar 20 kali-an. Tapi uniknya\"",
          "Andi: \"Uniknya ?\"",
          "Anjas: \"Uniknya ya hanya bagian kaki; bagian punggung ke bawah yang sering patah tulang. Dan mulai dari kecil saat saya masih balita belajar duduk menangis. Saya belajar duduk, belajar berdiri tiba-tiba nangis gak jelas, ternyata patah. Dan kemudian kalau misalkan saya lagi ngambil mainan terus, ternyata tiba-tiba patah. Nah, itu yang menyebabkan saya ada semacam kelainan. Jadi pertumbuhan tulang saya itu tumbuh bengkok di kedua kaki saya.\"",
          "Andy: \"Tapi sekarang setelah dewasa begini ?\"",
          "Anjas: \"Alhamdulillah, sering jatuh juga dan alhamdulillah, tidak apa-apa. Alhamdulillah.\"",
          "Andy: \"Kalau sekarang sekolah, kuliah atau kerja ?\"",
          "Anjas: \"Sekarang alhamdulillah, saya mahasiswa aktif di Universitas Brawijaya fakultas ilmu komputer.\"",
          "Andy: \"Semester berapa ?\"",
          "Anjas: \"Semester 7 bang Andy.\"",
          "Andy: \"Semester 7.\"",
          "Anjas: \"Alhamdulillah mau selesai.\"",
          "Andy: \"Anjas ceritakan kira-kira kenapa sampai aku ngundang kamu ke acara ini !\"",
          "Anjas: \"Jadi alhamdulillah, saya adalah mahasiswa Universitas Brawijaya yang total sudah mungkin sekitar 9 penghargaan, maksudnya 9 penghargaan internasional dari Indonesia dan internasional. Mulai dari medali perungu bang Andy hingga medali emas. Total ada 9 dan dari sertifikat internasional saya dapatkan di angka 17 sertifikat internasional.\"",
          "Andy: \"Sementara aku satu aja gak pernah dapet ya ? Mulai iri ni, mulai iri aku.\"",
          "Anjas: \"Alhamdulillah, Anjas di sini lolos di program, salah satu program beasiswa dari Kemendan luar negeri Amerika Serikat. tepatnya. Tepatnya nanti di bulan September Anjas akan berangkat ke Amerika Serikat di program Kemendan selama lima minggu bang Andy.\"",
          "Andy: \"Dimana, dimana ini ?\"",
          "Anjas: \"Anjas ditempatkan di University Nebraska of Omaha di Nebraska. Kemudian di dua hari terakhir, Anjas akan diundang ke White House di Gedung Putih berjumpa dengan Presiden.\"",
          "Andy: \"Tapi kalau sekolah sih mungkin akan sama kita. Kamu Nebraska tadi ?\"",
          "Anjas: \"Nebraska\"",
          "Andy: \"Saya di LA.\"",
          "Anjas: \"Los Angeles ?\"",
          "Andy: \"Lenteng Agung.\"",
          "Anjas: \"Hah hah\"",
          "Andy: \"Baik, supaya gak penasaran lebih baik kita liat dulu liputan berikut ini.\"",
          "Keterbatasan fisik tak lagi membuat Anjas Pramono berkecil hati, mahasiswa sistem informasi ilmu komputer Universitas Brawijaya Malang Jawa Timur ini. Berhasil menciptakan aplikasi berbasis android bernama DivoDev sebuah kamus bahasa isyarat. Melihat terbatasnya akses tunarungu dalam berkomunikasi, DivoDev mengubah bahasa Inggris atau Indonesia menjadi gambar bahasa isyarat.",
          "Dengan aplikasi DivoDev, Anjas berharap masyarakat akan lebih mudah dalam mempelajari bahasa isyarat untuk berkomunikasi dengan penyandang tunarungu. Aplikasi DivoDev pun telah meraih penghargaan medali perak dalam event International Innovation, Design & Articulation di Universitas Teknologi MARA Arau; Perlis, Malaysia dan medali emas dari University of Malaya. Atas prestasinya itu, Anjas Pramono mendapatkan beasiswa dari University of Nebraska Omaha, US. Anjas akan mengikuti pendidikan selama lima pekan dan mempresentasikan aplikasi rancangannya di Gedung Putih, Amerika Serikat.",
          "Andy: \"Anjas ada berapa aplikasi yang sudah kamu buat ?\"",
          "Anjas: \"Total saya sudah buat 5 aplikasi, lebih tepatnya saya dengan tim ya.\"",
          "Andy: \"Dengan tim\"",
          "Anjas: \"Ada temen-temen saya yang juga bantu saya.\"",
          "Andy: \"Iya\"",
          "Anjas: \"Itu kita membuat semacam tim untuk membuat aplikasi-aplikasi itu.\"",
          "Andy: \"Yang sudah jadi ?\"",
          "Anjas: \"Yang sudah jadi ada namanya DivoDev tadi yang sudah disebutkan. Itu dari bahasa Indonesia atau bahasa Inggris kita rubah menjadi bahasa isyarat.\"",
          "Andy: \"Iya, nanti peragakan ya !\"",
          "Anjas: \"Iya\"",
          "Andy: \"Pada kesempatan ini supaya penonton tahu juga apa manfaat dari aplikasi DivoDev. Nah, belum lagi nanti ada aplikasi-aplikasi lain yang sedang dalam progres. Kalau gak salah ya.\"",
          "Anjas: \"Iya\"",
          "Anjas: \"Harapan saya sebagai ladang pahala amal ibadah saya di duniawi karena saya memang ingin mengedarkan aplikasi ini secara gratis supaya bisa diakses seluruh masyarakat Indonesia.\""
      ],
      "insertedAt": "2022-12-08T13:48:14.321Z",
      "updatedAt": "2022-12-08T14:16:12.045Z"
  },
  {
      "id": "xSUZwOlBw6FGJ_Y",
      "title": "KISAH INSPIRATIF 4 TEMAN DISABILITAS",
      "link": "https://www.youtube.com/embed/jcB5-fsHn7M",
      "desc": [
          "Halo, teman-teman semua. Masih sehat ? Saya ingin bertanya, apakah disabilitas fisik bisa sukses ? Tapi dengan melihat fisik yang disabilitas banyak kekurangan dan hambatannya. Mau sukses pasti susah. Ah, siapa bilang ? Disabilitas fisik sukses ada loh. Ada 4 orang memiliki bisnis sendiri buktinya sudah jelas. ",
          "Yang pertama namanya Habibie Afsyah. Dulu ia lahir dengan disabilitas saraf motorik seperti kesulitan bergerak. Dia selalu menggunakan kursi roda dan sangat pintar. Setelah lulus SMA, ibunya menyuruh dia untuk mengambil kursus internet marketing di Singapura selama tiga minggu.",
          "Sesudah ikut pelatihan tersebut, ia pulang ke Indonesia dan langsung bergabung dengan situs bisnis Amazon dan berhasil sukses dari situ. Satu bulan, ia bisa mendapatkan banyak uang dan uang tersebut digunakan untuk membangun Yayasan Habibie Afsyah yang bertujuan untuk membantu teman-teman disabilitas supaya kemampuan mereka bisa diasah dengan baik.",
          "Yang kedua Tarjono Slamet. Ia adalah seorang disabilitas daksa. Sebetulnya dulu, dia orang normal. Tetapi karena waktu bekerja di PLN, dia kesetrum hingga tangan dan kakinya tidak dapat berfungsi lagi. Ia pernah mengalami stres selama 2 tahun, tapi terus berusaha untuk bisa bangkit. Akhirnya ia berhasil dan menjadi sukses melalui bisnis kerajinan kayu yang pernah diekspor ke luar negeri seperti Australia, Malaysia, Selandia Baru, dan lain-lain. Ia dapat meraup keuntungan 150 juta per bulan.",
          "Yang ketiga. Ia bernama Fanny, disabilitas kaki. Ia punya bisnis kecantikan sendiri bernama Thisable Beauty Care yang dibangun tahun 2016. Ia berasal dari Pontianak dan dulu pernah bekerja di bank, tetapi saat itu disuruh keluar karena ia memakai seragam yang berbeda dengan yang lainnya. Akhirnya ia pindah ke Jakarta dan berhasil sukses. Dengan bekerja di Thisable yang merupakan perusahaan milik Angkie Yudistia.",
          "Yang keempat bernama Irma Suyanti, seorang disabilitas fisik karena sakit polio. Ia sukses memiliki bisnis pabrik karet dan punya 2.500 orang karyawan. Wow. Pabrik ini pertama kali dibangun pada tahun 1999. Awalnya hanya usaha biasa saja. Ia hanya menawarkan produknya ke pasar dan tetangga. Lama-kelamaan bisnisnya berkembang sampai bisa sukses dan mendapat uang ratusan juta dalam satu bulan. Wow. Nah tadi itu, 4 contoh teman disabilitas yang sudah sukses. Kalian mau sukses ? Ayo semangat. Sampai jumpa lagi."
      ],
      "insertedAt": "2022-12-08T14:05:20.788Z",
      "updatedAt": "2022-12-08T14:21:06.943Z"
  },
  {
      "id": "A37Sqo2tRkd2v5M",
      "title": "Kisah Anak Penyandang Disabilitas yang Berprestasi",
      "link": "https://www.youtube.com/embed/4pD8UcRevi8",
      "desc": [
          "Sekolah Luar Bisa Santi Rama didirikan pada 1970 oleh Ny. JS. Nasution dan Prof. dr. Hendarto Hendarmin (dokter THT).",
          "Yayasan ini diresmikan pada 14 Februari 1976.",
          "Salah satu muridnya yaitu Muhammad Faiz berprestasi dalam bidang desain grafis hingga memenangkan lomba di tingkat nasional.",
          "Faiz: \"Nama saya Muhammad Faiz. Saya kelas 9. Saya bersekolah di Santi Rama.\"",
          "Boni (Wali kelas Faiz): \"Selama masa pengajaran, si Faiz di kelas itu bisa, bagus dengan teman-temannya.\"",
          "Restu (Guru Pembina Faiz): \"Awal-awalnya dipilih dari sekolah untuk mengikuti pemilihan tingkat Jakarta Selatan dulu awalnya. Lalu Faiz mendapat juara satu. Lalu lanjut ke tingkat DKI Jakarta. Lalu pas tingkat DKI Jakarta juara satu lagi. Akhirnya bisa lanjut ke tingkat nasional.\"",
          "Satriawan Chan (Ayah Faiz): \"Semangatnya Faiz sudah cukup lama menyenangi dunia gambar mengambar sejak dia masih TK dulu sudah senang mengambar menggunakan komputer. Kemudian memang saat ini mungkin lebih terarah dan terfokus dengan adanya pembina dan semua.\"",
          "Faiz: \"Aku kesulitan saat buat animasi, dulu aku tidak bisa, tapi lama-lama menjadi bisa.\"",
          "Boni (Wali kelas Faiz): \"Kalau mengenai Faiz, dia itu kurang mampu kalau dipertandingkan belum, tapi dia bisa mengikuti. Tapi mungkin mereka di bidang lain dia lebih bagus lagi selain olahraga.\"",
          "Restu (Guru Pembina Faiz): \"Jadinya, untuk mempersiapkan lombanya. Jadinya Faiz itu, sebelum lomba kita latihan dari direktorat sendiri dari dinas pendidikan kita latihan selama satu minggu. Lalu Faiz. Setelah jum'at selesai latihan langsung hari minggunya kita berangkat lomba. Dia sangat semangat sekali, tahu gitu bahwasanya juara satu dia akan membuat bangga orang tuanya, membuat bangga teman-temannya. Jadinya gitu, dia semangat banget buat ngikutin lomba ini.\"",
          "Satriawan Chan (Ayah Faiz): \"Untuk potensi kami menyadari, tapi kalau untuk memenangkan juara sampai tingkat nasional memang itu di luar dugaan kami karena pesertanya pasti cukup banyak dan mempunyai kemampuan yang lebih dari Faiz.\"",
          "Faiz: \"Saya senang bermain dengan semua teman-teman dan guru di sekolah karena semua baik-baik dan tidak ada masalah. Saya juga tidak bermasalah dengan guru.\"",
          "Restu (Guru Pembina Faiz): \"Karena dia awalnya ada bakat dan disertai dengan kerja keras maka hasilnya maksimal. Dia bisa mendapet juara tingkat nasional lomba desain grafis SMP ini.\"",
          "Satriawan Chan (Ayah Faiz): \"Kami, mamanya dan saya itu selalu mensupport dia untuk bisa mampu dengan orang-orang yang umumnya normal sehingga jangan sampe kalah dengan yang normal. Jadi, selalu kami support.\"",
          "Faiz: \"Harus rajin belajar karena nanti lama-kelamaan akan bisa pintar dan naik kelas.\""
      ],
      "insertedAt": "2022-12-08T14:11:35.718Z",
      "updatedAt": "2022-12-08T14:24:59.723Z"
  },
  {
      "id": "fLhqiJ5_MCqOu4W",
      "title": "Disabilitas Bukan Penghalang",
      "link": "https://www.youtube.com/embed/XfnQwsS5zDE",
      "desc": [
          "Pernah juga ditolak oleh penerbit karena karya saya tidak sesuai dengan keinginan mereka. Kemudian pernah juga diremehkan temen-temen. Pada akhirnya menjadi penulis itu hal yang bisa dikatakan hal yang mustahil lah ya.",
          "Orang tua Ayu Imtyas: \"Kita ya sebagai orang tua ya. Kami sudah berusaha semaksimal kami.\"",
          "Terlebih lagi saya ingin membuktikan kepada dunia bahwa seorang disabilitas bukan menjadi sebuah hal yang aneh atau dipandang remeh di masyarakat.",
          "Hai, kawan muda luar biasa.",
          "Saya Ayu Imtyas Rusdiansyah seorang penulis berasal dari Gresik berusia 22 tahun. Pada awalnya saya menulis sebenarnya ingin membuktikan kepada dunia bahwa seorang penderita Writer's Cramp Dystonia seperti saya. Itu meskipun tidak bisa menulis atau misalnya melakukan hal-hal sesuatu yang dianggap seseorang itu sederhana. Tapi kita juga bisa membuat sebuah karya nah buktinya saya. Saya saat ini menjadi seorang penulis meskipun Writer's Cramp Dystonia itu tidak bisa menulis. Dimulai dari saya membuat karangan pendek. Kemudian membuat karya tulis berupa esai. Nah, pada akhirnya keterusan. Jadi membikin buku. Sampai sekarang sudah 30 buku saya terbitkan.",
          "Saya memiliki pengalaman yang membuat down pada saat itu. Pernah juga ditolak oleh penerbit karena karya saya tidak sesuai dengan keinginan mereka. Kemudian pernah juga diremehkan teman-temen bahwa seorang Write's Cramp Dystonia itu kok bisa jadi penulis. Mereka pada akhirnya heran gitu ya. Tapi saya ingin membuktikan kepada dunia bahwa saya itu bisa.",
          "Orang tua Ayu Imtyas: \"Kita sebagai orang tua ya tentunya sudah berusaha semaksimal kami dengan kondisi yang dialami anak kami. Dokter sarafnya itu memvonis ini gak diketemukan penyakitnya.\"",
          "Saya kesulitan untuk menulis nah kemudian saya mencoba mencari alternatif yakni dengan menggunakan laptop dalam saya membuat karya. Kita tu semuanya meskipun dalam keterbatasan, tapi kita juga bisa untuk maju, itu juga bisa. Sampai saat ini saya berupaya untuk mengembangkan diri saya agar bisa terus maju dan berkembang. Terlebih lagi saya ingin membanggakan kedua orang tua saya.",
          "Saya juga ingin membuktikan kepada dunia bahwa seorang disabilitas atau Write's Cramp Dystonia bukan menjadi sebuah hal yang aneh atau dipandang remeh di masyarakat. Orang tua saya merupakan sosok inspirasi yang sangat mendukung saya sampai saat ini. Di tengah beberapa keterbatasan saya dan juga lika-liku perjuangan kehidupan saya. Orang tua saya yang nomor satu untuk dalsm hal mendukung saya sampai saya pada akhirnya menjadi seorang penulis sampai saat ini.",
          "Orang tua Ayu Imtyas: \"Ya, gini untuk memberikan support untuk anak kami yang penting kami bangun dari ini ya motivasi dari dalam diri anak. Jadi, kita bangun kepercayaan dirinya dan kita selalu mendampingi. Sehingga anak itu selalu merasa ini ya tetap terlindungi dan kita juga tetap selalu berusaha dalam banyak hal. Anak ini jangan sampai down ya. Jadi, motivasi apapun kita lakukan yang jelas kita bangun motivasi dalam dirinya dulu.\"",
          "Kita sebagai generasi penerus bangsa harus memiliki semangat untuk membanggakan dan menghasilkan sebuah karya yang bermanfaat untuk bangsa dan diri kita sendiri tentunya. Dan juga saya juga ingin agar semua anak-anak di Indonesia dan generasi penerus bangsa tetap semangat. Meskipun di masa pandemi saat ini, kita harus terus bisa berkarya dan mengembangkan passion yang kita miliki. Indonesia bangkit, muda luar biasa."
      ],
      "insertedAt": "2022-12-08T14:16:43.723Z",
      "updatedAt": "2022-12-08T14:25:51.548Z"
  }
]

module.exports =  videos;
